from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from google import genai
from google.genai import types
from PIL import Image

DEFAULT_QA_MODEL = os.getenv("KHYRAT_IMAGE_QA_MODEL", "gemini-3.1-flash-lite")
# QA is advisory. Only clearly unusable or materially unrelated images should regenerate.
QA_MIN_COMPOSITION = int(os.getenv("KHYRAT_IMAGE_QA_MIN_COMPOSITION", "55"))
QA_MIN_RELEVANCE = int(os.getenv("KHYRAT_IMAGE_QA_MIN_RELEVANCE", "55"))
QA_MIN_OVERALL = int(os.getenv("KHYRAT_IMAGE_QA_MIN_OVERALL", "60"))
QA_HARD_REJECT_RELEVANCE = int(os.getenv("KHYRAT_IMAGE_QA_HARD_REJECT_RELEVANCE", "25"))
QA_HARD_REJECT_OVERALL = int(os.getenv("KHYRAT_IMAGE_QA_HARD_REJECT_OVERALL", "25"))
QA_MAX_RETRIES = max(1, int(os.getenv("KHYRAT_IMAGE_QA_MAX_RETRIES", "1")))
ALLOWED_BRAND_TEXT = "اسأل محمود - مستشار قانوني للشركات"


class ImageQAError(RuntimeError):
    """Raised when visual QA cannot safely complete."""


def _extract_json(raw: str) -> dict[str, Any]:
    text = (raw or "").strip()
    text = re.sub(r"^\`\`\`(?:json)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*\`\`\`$", "", text)
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start < 0 or end <= start:
            raise ImageQAError(f"Gemini image QA returned invalid JSON: {text[:1200]}")
        try:
            data = json.loads(text[start:end + 1])
        except json.JSONDecodeError as exc:
            raise ImageQAError(f"Gemini image QA returned malformed JSON: {text[:1200]}") from exc
    if not isinstance(data, dict):
        raise ImageQAError("Gemini image QA response is not an object.")
    return data


def _hard_checks(image_path: Path) -> dict[str, Any]:
    try:
        with Image.open(image_path) as image:
            width, height = image.size
            ratio = width / height if height else 0
    except Exception as exc:
        raise ImageQAError(f"Could not open generated image for QA: {exc}") from exc

    ratio_ok = width > 0 and height > 0 and abs(ratio - 0.8) <= 0.003
    return {
        "width": width,
        "height": height,
        "aspect_ratio": round(ratio, 5),
        "aspect_ratio_ok": ratio_ok,
    }


def _normalize_score(value: Any, fallback: int = 0) -> int:
    try:
        return max(0, min(100, int(value)))
    except (TypeError, ValueError):
        return fallback


def _build_prompt(topic: str, image_brief: str, hard: dict[str, Any], reference_count: int, image_mode: str) -> str:
    return f"""
You are the final visual QA editor for a professional Egyptian legal-content publishing engine.

Inspect the FINAL rendered image, not the original generation response.

LEGAL TOPIC:
{topic}

ORIGINAL VISUAL BRIEF:
{image_brief}

HARD IMAGE CHECK:
- Final dimensions: {hard['width']}x{hard['height']}
- Target aspect ratio: 4:5 (0.8)
- Local aspect-ratio check: {'PASS' if hard['aspect_ratio_ok'] else 'FAIL'}
- Image mode: CONTEXT_ONLY
- Character reference images: none

REFERENCE IMAGE RULE:
No character-reference images are supplied or required. Evaluate the generated scene from the legal topic and visual brief only.
The generated scene must be new and directly communicate the legal situation without relying on a recurring-person identity.

CONTEMPORARY SCENE RULE:
For current legal topics, assess whether the image shows a believable present-day setting and the exact action or evidence described in the brief. Use only the time period, locations, people, devices, and documents directly supported by the legal topic and visual brief. Prefer ordinary contemporary settings for current legal situations.
For ordinary present-day legal topics, reject period-drama styling, monumental ancient architecture, royal costume, carved historical symbols, papyrus-like materials, or antiquity-inspired decoration unless the legal topic explicitly concerns historical artifacts or heritage. A generic legal topic is never a reason to introduce a historical visual style.

BRAND OVERLAY RULE:
A small bottom-right overlay reading "{ALLOWED_BRAND_TEXT}" plus the Facebook "f" badge is intentionally
added by the code after generation. This exact overlay is ALLOWED and must NOT be counted as bad generated text.
Any other visible generated text, fake Arabic/English lettering, gibberish, watermark, logo, headline,
caption, sign, document writing, or typography is a defect.

CHECK THESE FIVE THINGS:
1. COMPOSITION: Is the visual clean and professionally composed for a 4:5 social feed?
   Is the focal subject visible? Is the crop safe? Are important hands, faces, documents, and actions
   not awkwardly cut? Is there enough visual breathing room? Is the scene understandable without text?
2. GENERATED TEXT: Detect any text that was generated by the image model. Ignore ONLY the intentional
   bottom-right brand overlay described above. If any other text exists, mark text_detected=true and list it.
3. LEGAL RELEVANCE: Does the visual directly depict the legal situation in the topic/brief, rather than
   a generic lawyer, courthouse, scales, gavel, legal background, or unrelated office scene?
4. ANATOMY AND VISUAL INTEGRITY: Check for warped faces, asymmetrical eyes, malformed teeth, distorted ears, duplicate limbs, extra fingers, fused fingers, missing fingers, unnatural wrists, twisted arms, duplicated objects, or obvious generative artifacts. Treat obvious anatomy defects as a REGENERATE signal and explain them in composition_findings or issues
DECISION:
PASS when the image is usable for publication and materially related to the topic.
REGENERATE only when the scene is clearly unrelated, unusable, badly malformed, or contains serious generated text that damages the asset.
Do not reject a usable image merely because composition, styling, or interpretation is imperfect.
The image is a first-class publishing asset. QA is advisory and should preserve a usable image whenever possible.

Return JSON only:
{{
  "decision": "PASS|REGENERATE",
  "composition_score": 0,
  "relevance_score": 0,
  "reference_score": 0,
  "overall_score": 0,
  "text_detected": false,
  "detected_text": [],
  "composition_findings": [],
  "relevance_findings": [],
  "reference_findings": [],
  "issues": [],
  "regeneration_prompt": "short English instructions for the next generation attempt"
}}
""".strip()


def qa_image(
    *,
    api_key: str,
    image_path: str,
    topic: str,
    image_brief: str,
    model: str | None = None,
    image_mode: str = "CONTEXT_ONLY",
) -> dict[str, Any]:
    if not api_key:
        raise ImageQAError("GEMINI_API_KEY is missing for image QA.")

    path = Path(image_path)
    if not path.is_file():
        raise ImageQAError(f"Image does not exist for QA: {path}")

    hard = _hard_checks(path)
    image_mode = "CONTEXT_ONLY"
    references = []

    if not hard["aspect_ratio_ok"]:
        return {
            "decision": "REGENERATE",
            "composition_score": 0,
            "relevance_score": 0,
            "reference_score": 0,
            "overall_score": 0,
            "text_detected": False,
            "detected_text": [],
            "composition_findings": ["Final image is not 4:5."],
            "relevance_findings": [],
            "reference_findings": [],
            "issues": [f"Expected 4:5 but received {hard['width']}x{hard['height']}."],
            "regeneration_prompt": "Preserve the same story but produce a portrait 4:5 composition with a safe social-feed crop.",
            "hard_checks": hard,
        }

    client = genai.Client(api_key=api_key)
    contents: list[Any] = [
        _build_prompt(topic, image_brief, hard, len(references), image_mode),
        types.Part.from_bytes(data=path.read_bytes(), mime_type="image/jpeg"),
    ]

    for ref in references:
        try:
            mime = {
                ".jpg": "image/jpeg",
                ".jpeg": "image/jpeg",
                ".png": "image/png",
                ".webp": "image/webp",
                ".heic": "image/heic",
                ".heif": "image/heif",
                ".avif": "image/avif",
            }.get(ref.suffix.lower())
            if mime:
                contents.append(types.Part.from_bytes(data=ref.read_bytes(), mime_type=mime))
        except OSError as exc:
            print(f"Image QA reference warning for {ref.name}: {exc}")

    try:
        response = client.models.generate_content(
            model=(model or DEFAULT_QA_MODEL).strip() or DEFAULT_QA_MODEL,
            contents=contents,
            config=types.GenerateContentConfig(max_output_tokens=1400),
        )
    except Exception as exc:
        raise ImageQAError(f"Gemini visual QA request failed: {exc}") from exc

    data = _extract_json(getattr(response, "text", ""))
    decision = str(data.get("decision", "")).strip().upper()
    if decision not in {"PASS", "REGENERATE"}:
        decision = "REGENERATE"

    data["decision"] = decision
    data["composition_score"] = _normalize_score(data.get("composition_score"))
    data["relevance_score"] = _normalize_score(data.get("relevance_score"))
    data["reference_score"] = 100
    data["overall_score"] = _normalize_score(data.get("overall_score"))
    data["text_detected"] = bool(data.get("text_detected", False))
    for field in ("detected_text", "composition_findings", "relevance_findings", "reference_findings", "issues"):
        value = data.get(field, [])
        if not isinstance(value, list):
            value = [str(value)] if value else []
        data[field] = [str(item).strip() for item in value if str(item).strip()]
    data["regeneration_prompt"] = str(data.get("regeneration_prompt", "")).strip()
    data["hard_checks"] = hard
    data["image_mode"] = image_mode

    critical_failures = []
    # Soft thresholds are warnings. Hard thresholds are the regeneration boundary.
    if data["relevance_score"] < QA_HARD_REJECT_RELEVANCE:
        critical_failures.append(f"Legal relevance is critically low ({data['relevance_score']}).")
    if data["overall_score"] < QA_HARD_REJECT_OVERALL:
        critical_failures.append(f"Overall usability is critically low ({data['overall_score']}).")
    if data["text_detected"] and len(data.get("detected_text", [])) >= 2:
        critical_failures.append("Multiple unexpected generated text elements detected.")
    if any("unusable" in item.casefold() or "severely malformed" in item.casefold() for item in data.get("issues", [])):
        critical_failures.append("Severe visual integrity defect detected.")

    if critical_failures:
        data["decision"] = "REGENERATE"
    else:
        data["decision"] = "PASS"
        soft_warnings = []
        if data["composition_score"] < QA_MIN_COMPOSITION:
            soft_warnings.append(f"Composition advisory below {QA_MIN_COMPOSITION}.")
        if data["relevance_score"] < QA_MIN_RELEVANCE:
            soft_warnings.append(f"Relevance advisory below {QA_MIN_RELEVANCE}.")
        if data["overall_score"] < QA_MIN_OVERALL:
            soft_warnings.append(f"Overall advisory below {QA_MIN_OVERALL}.")
        data["issues"] = soft_warnings + data["issues"]
    data["issues"] = critical_failures + data["issues"]
    if data["decision"] == "REGENERATE" and not data["regeneration_prompt"]:
        data["regeneration_prompt"] = "Fix every listed visual defect while preserving the exact legal story and the identity reference."

    # Attach QA outcome to the generation sidecar so a bad image can be traced
    # to the exact provider, prompt hash, and final file hash.
    provenance_path = path.with_suffix(path.suffix + ".provenance.json")
    if provenance_path.is_file():
        try:
            provenance = json.loads(provenance_path.read_text(encoding="utf-8"))
            provenance["qa_decision"] = data["decision"]
            provenance["qa_model"] = (model or DEFAULT_QA_MODEL).strip() or DEFAULT_QA_MODEL
            provenance["qa_overall_score"] = data["overall_score"]
            provenance["qa_relevance_score"] = data["relevance_score"]
            provenance["qa_issues"] = data["issues"]
            provenance["qa_checked_image_sha256"] = __import__("hashlib").sha256(path.read_bytes()).hexdigest()
            provenance_path.write_text(
                json.dumps(provenance, ensure_ascii=False, indent=2) + "\\n",
                encoding="utf-8",
            )
        except Exception as exc:
            print(f"Image provenance QA update warning: {exc}")

    return data


def summarize_qa(data: dict[str, Any]) -> str:
    issues = data.get("issues") or []
    return " | ".join(str(x).strip() for x in issues if str(x).strip())[:1500]
