from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from google import genai
from google.genai import types
from PIL import Image

DEFAULT_QA_MODEL = os.getenv("KHYRAT_IMAGE_QA_MODEL", "gemini-3.1-flash-lite")
QA_MIN_COMPOSITION = int(os.getenv("KHYRAT_IMAGE_QA_MIN_COMPOSITION", "75"))
QA_MIN_RELEVANCE = int(os.getenv("KHYRAT_IMAGE_QA_MIN_RELEVANCE", "85"))
QA_MIN_OVERALL = int(os.getenv("KHYRAT_IMAGE_QA_MIN_OVERALL", "80"))
QA_MAX_RETRIES = max(1, int(os.getenv("KHYRAT_IMAGE_QA_MAX_RETRIES", "2")))
REFERENCE_DIR = Path(os.getenv("KHYRAT_CHARACTER_REFERENCE_DIR", "assets/reference"))
REFERENCE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".heic", ".heif", ".avif"}
ALLOWED_BRAND_TEXT = "اسأل محمود - مستشار قانوني للشركات"


class ImageQAError(RuntimeError):
    """Raised when visual QA cannot safely complete."""


def _extract_json(raw: str) -> dict[str, Any]:
    text = (raw or "").strip()
    text = re.sub(r"^\`\`\`(?:json)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*\`\`\`$", "", text)
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start < 0 or end <= start:
            raise ImageQAError(f"Gemini image QA returned invalid JSON: {text[:1200]}")
        try:
            data = json.loads(text[start:end + 1])
        except json.JSONDecodeError as exc:
            raise ImageQAError(f"Gemini image QA returned malformed JSON: {text[:1200]}") from exc
    if not isinstance(data, dict):
        raise ImageQAError("Gemini image QA response is not an object.")
    return data


def _reference_files() -> list[Path]:
    if not REFERENCE_DIR.is_dir():
        return []
    return sorted(
        p for p in REFERENCE_DIR.iterdir()
        if p.is_file() and p.suffix.lower() in REFERENCE_EXTENSIONS
    )


def _hard_checks(image_path: Path) -> dict[str, Any]:
    try:
        with Image.open(image_path) as image:
            width, height = image.size
            ratio = width / height if height else 0
    except Exception as exc:
        raise ImageQAError(f"Could not open generated image for QA: {exc}") from exc

    ratio_ok = width > 0 and height > 0 and abs(ratio - 0.8) <= 0.003
    return {
        "width": width,
        "height": height,
        "aspect_ratio": round(ratio, 5),
        "aspect_ratio_ok": ratio_ok,
    }


def _normalize_score(value: Any, fallback: int = 0) -> int:
    try:
        return max(0, min(100, int(value)))
    except (TypeError, ValueError):
        return fallback


def _build_prompt(topic: str, image_brief: str, hard: dict[str, Any], reference_count: int, image_mode: str) -> str:
    return f"""
You are the final visual QA editor for a professional Egyptian legal-content publishing engine.

Inspect the FINAL rendered image, not the original generation response.

LEGAL TOPIC:
{topic}

ORIGINAL VISUAL BRIEF:
{image_brief}

HARD IMAGE CHECK:
- Final dimensions: {hard['width']}x{hard['height']}
- Target aspect ratio: 4:5 (0.8)
- Local aspect-ratio check: {'PASS' if hard['aspect_ratio_ok'] else 'FAIL'}
- Image mode: {image_mode}\n- Character reference images supplied for comparison: {reference_count}

REFERENCE IMAGE RULE:
If image mode is REFERENCE_SUBJECT, the attached reference photos are the identity source for the recurring subject. Compare only stable
identity traits when the recurring subject appears. If image mode is CONTEXT_ONLY, do not depict the recurring lawyer as the subject.\nDo not require the scene, pose, wardrobe, camera,
background, furniture, lighting, or framing to match the references. The generated scene must be new.

BRAND OVERLAY RULE:
A small bottom-right overlay reading "{ALLOWED_BRAND_TEXT}" plus the Facebook "f" badge is intentionally
added by the code after generation. This exact overlay is ALLOWED and must NOT be counted as bad generated text.
Any other visible generated text, fake Arabic/English lettering, gibberish, watermark, logo, headline,
caption, sign, document writing, or typography is a defect.

CHECK THESE FOUR THINGS:
1. COMPOSITION: Is the visual clean and professionally composed for a 4:5 social feed?
   Is the focal subject visible? Is the crop safe? Are important hands, faces, documents, and actions
   not awkwardly cut? Is there enough visual breathing room? Is the scene understandable without text?
2. GENERATED TEXT: Detect any text that was generated by the image model. Ignore ONLY the intentional
   bottom-right brand overlay described above. If any other text exists, mark text_detected=true and list it.
3. LEGAL RELEVANCE: Does the visual directly depict the legal situation in the topic/brief, rather than
   a generic lawyer, courthouse, scales, gavel, legal background, or unrelated office scene?
4. REFERENCE CONSISTENCY: If image mode is REFERENCE_SUBJECT, compare the face directly against the attached reference photos.
   This is an identity gate, not a generic attractiveness/similarity judgment. Check facial proportions, eyes/brows, nose,
   mouth/lip shape, jaw/chin, hairline, hairstyle, beard pattern, skin tone, and overall facial geometry.
   If you cannot confidently conclude that the same person is depicted, score reference_score below 80 and choose REGENERATE.
   A generic Egyptian professional man is NOT a pass, even if age, hair, beard, and skin tone are broadly similar.
   If the references do not contain enough information to establish identity, report the limitation as advisory; never block publication.

DECISION:
PASS only when all critical requirements are satisfied.
REGENERATE when the image can be fixed by changing the visual prompt.
Never block publication; QA is advisory only.

Return JSON only:
{{
  "decision": "PASS|REGENERATE",
  "composition_score": 0,
  "relevance_score": 0,
  "reference_score": 0,
  "overall_score": 0,
  "text_detected": false,
  "detected_text": [],
  "composition_findings": [],
  "relevance_findings": [],
  "reference_findings": [],
  "issues": [],
  "regeneration_prompt": "short English instructions for the next generation attempt"
}}
""".strip()


def qa_image(
    *,
    api_key: str,
    image_path: str,
    topic: str,
    image_brief: str,
    model: str | None = None,
    image_mode: str = "REFERENCE_SUBJECT",
) -> dict[str, Any]:
    if not api_key:
        raise ImageQAError("GEMINI_API_KEY is missing for image QA.")

    path = Path(image_path)
    if not path.is_file():
        raise ImageQAError(f"Image does not exist for QA: {path}")

    hard = _hard_checks(path)
    image_mode = (image_mode or "REFERENCE_SUBJECT").strip().upper()
    if image_mode != "REFERENCE_SUBJECT":
        return {
            "decision": "REGENERATE",
            "composition_score": 0,
            "relevance_score": 0,
            "reference_score": 0,
            "overall_score": 0,
            "text_detected": False,
            "detected_text": [],
            "composition_findings": [],
            "relevance_findings": [],
            "reference_findings": ["Preferred reference-subject mode was not selected; advisory only."],
            "issues": ["Publication is not blocked by image mode or QA."],
            "regeneration_prompt": "",
            "hard_checks": hard,
            "image_mode": image_mode,
        }
    references = _reference_files()

    if not hard["aspect_ratio_ok"]:
        return {
            "decision": "REGENERATE",
            "composition_score": 0,
            "relevance_score": 0,
            "reference_score": 0,
            "overall_score": 0,
            "text_detected": False,
            "detected_text": [],
            "composition_findings": ["Final image is not 4:5."],
            "relevance_findings": [],
            "reference_findings": [],
            "issues": [f"Expected 4:5 but received {hard['width']}x{hard['height']}."],
            "regeneration_prompt": "Preserve the same story but produce a portrait 4:5 composition with a safe social-feed crop.",
            "hard_checks": hard,
        }

    client = genai.Client(api_key=api_key)
    contents: list[Any] = [
        _build_prompt(topic, image_brief, hard, len(references), image_mode),
        types.Part.from_bytes(data=path.read_bytes(), mime_type="image/jpeg"),
    ]

    for ref in references:
        try:
            mime = {
                ".jpg": "image/jpeg",
                ".jpeg": "image/jpeg",
                ".png": "image/png",
                ".webp": "image/webp",
                ".heic": "image/heic",
                ".heif": "image/heif",
                ".avif": "image/avif",
            }.get(ref.suffix.lower())
            if mime:
                contents.append(types.Part.from_bytes(data=ref.read_bytes(), mime_type=mime))
        except OSError as exc:
            print(f"Image QA reference warning for {ref.name}: {exc}")

    try:
        response = client.models.generate_content(
            model=(model or DEFAULT_QA_MODEL).strip() or DEFAULT_QA_MODEL,
            contents=contents,
            config=types.GenerateContentConfig(max_output_tokens=1400),
        )
    except Exception as exc:
        raise ImageQAError(f"Gemini visual QA request failed: {exc}") from exc

    data = _extract_json(getattr(response, "text", ""))
    decision = str(data.get("decision", "")).strip().upper()
    if decision not in {"PASS", "REGENERATE"}:
        decision = "REGENERATE"

    data["decision"] = decision
    data["composition_score"] = _normalize_score(data.get("composition_score"))
    data["relevance_score"] = _normalize_score(data.get("relevance_score"))
    data["reference_score"] = _normalize_score(data.get("reference_score"), 100 if image_mode == "CONTEXT_ONLY" else 0)
    data["overall_score"] = _normalize_score(data.get("overall_score"))
    data["text_detected"] = bool(data.get("text_detected", False))
    for field in ("detected_text", "composition_findings", "relevance_findings", "reference_findings", "issues"):
        value = data.get(field, [])
        if not isinstance(value, list):
            value = [str(value)] if value else []
        data[field] = [str(item).strip() for item in value if str(item).strip()]
    data["regeneration_prompt"] = str(data.get("regeneration_prompt", "")).strip()
    data["hard_checks"] = hard
    data["image_mode"] = image_mode

    critical_failures = []
    if data["text_detected"]:
        critical_failures.append("Unexpected generated text detected.")
    if data["composition_score"] < QA_MIN_COMPOSITION:
        critical_failures.append(f"Composition score below {QA_MIN_COMPOSITION}.")
    if data["relevance_score"] < QA_MIN_RELEVANCE:
        critical_failures.append(f"Legal relevance score below {QA_MIN_RELEVANCE}.")
    if image_mode == "REFERENCE_SUBJECT" and data["reference_score"] < 90:
        critical_failures.append("Reference identity score below 90 (advisory).")
    if data["overall_score"] < QA_MIN_OVERALL:
        critical_failures.append(f"Overall score below {QA_MIN_OVERALL}.")

    if critical_failures and data["decision"] == "PASS":
        data["decision"] = "REGENERATE"
    data["issues"] = critical_failures + data["issues"]
    if data["decision"] == "REGENERATE" and not data["regeneration_prompt"]:
        data["regeneration_prompt"] = "Fix every listed visual defect while preserving the exact legal story and the identity reference."

    return data


def summarize_qa(data: dict[str, Any]) -> str:
    issues = data.get("issues") or []
    return " | ".join(str(x).strip() for x in issues if str(x).strip())[:1500]
