from __future__ import annotations

from calendar import monthrange
from datetime import date

from src.sheets import get_values, insert_row_at_top, row_to_dict
from src.utils import parse_date

RECYCLE_MARKER = "MONTHLY_RECYCLE"
DEFAULT_POSTING_TIME = "14:00"

ANGLE_LIBRARY = [
    "خطأ شائع يقع فيه الناس وكيف يتجنبونه",
    "موقف واقعي قصير وما التصرف القانوني الصحيح",
    "متى يكون الحق ثابتًا ومتى قد يضيع؟",
    "أهم مستند أو دليل يحمي صاحب الحق",
    "ماذا تفعل خلال أول 24 ساعة من المشكلة؟",
    "الفرق بين التصور الشائع والحقيقة القانونية",
    "3 علامات تحذيرية قبل اتخاذ القرار",
    "متى تحتاج لمحامٍ ومتى يمكن اتخاذ خطوة أولية بنفسك؟",
    "أكثر سؤال يتكرر حول الموضوع وإجابته العملية",
    "كيف تنظر المحكمة عادةً للمشكلة بصورة مبسطة؟",
    "خطوة تبدو صحيحة لكنها قد تضر بموقفك",
    "مقارنة بين تصرفين ونتيجة كل منهما",
    "سيناريو عائلي أو عملي شائع مرتبط بالموضوع",
    "ما الذي يجب ألا توقع عليه أو تتنازل عنه؟",
    "Checklist عملية قبل بدء أي إجراء",
    "زاوية جديدة تركز على الوقاية قبل وقوع المشكلة",
]


def _month_key(value: str) -> str:
    try:
        return parse_date(value).strftime("%Y-%m")
    except Exception:
        return ""


def _even_days(year: int, month: int) -> list[int]:
    return [
        day
        for day in range(1, monthrange(year, month)[1] + 1)
        if day % 2 == 0
    ]


def _source_rows(values: list[list[str]]) -> list[dict[str, str]]:
    """Return usable original topics from the Sheet.

    The recycler deliberately does not require a previous month of PUBLISHED rows.
    This allows the automation to bootstrap from the existing content library.
    Rows generated by the recycler itself are excluded to prevent recycling a
    recycled topic forever.
    """
    result: list[dict[str, str]] = []
    seen: set[str] = set()

    for raw in values[1:]:
        row = row_to_dict(raw)
        notes = row.get("ملاحظات", "")
        if RECYCLE_MARKER in notes:
            continue

        topic = row.get("الموضوع", "").strip()
        if not topic or topic in seen:
            continue

        # A date is optional for the source library. The recycler can bootstrap
        # from topics that are already in the Sheet but were never published.
        if row.get("تاريخ النشر", "").strip():
            _month_key(row.get("تاريخ النشر", ""))

        seen.add(topic)
        result.append(row)

    return result


def _already_recycled(values: list[list[str]], month_key: str) -> bool:
    marker = f"{RECYCLE_MARKER}:{month_key}"
    return any(
        marker in row_to_dict(raw).get("ملاحظات", "")
        for raw in values[1:]
    )


def recycle_month_if_needed(
    *,
    service,
    spreadsheet_id: str,
    sheet_name: str,
    current: date,
) -> int:
    """Prepare the current month's recycled queue once.

    The queue is generated from all available original topics, not only from
    the previous month's PUBLISHED rows. If there are fewer source topics than
    required posting days, topics are reused in round-robin order while each
    post receives a different editorial angle.
    """
    values = get_values(
        service,
        spreadsheet_id,
        f"{sheet_name}!A:U",
    )

    current_key = current.strftime("%Y-%m")
    if _already_recycled(values, current_key):
        print(f"Monthly recycler: {current_key} is already prepared.")
        return 0

    sources = _source_rows(values)

    if not sources:
        print(
            "Monthly recycler: no original source topics found in the Sheet."
        )
        return 0

    days = [
        day
        for day in _even_days(current.year, current.month)
        if day >= current.day
    ]

    if not days:
        print(
            f"Monthly recycler: no future posting days remain in {current_key}."
        )
        return 0

    required_posts = len(days)
    available_topics = len(sources)

    if available_topics < required_posts:
        print(
            "Monthly recycler: available topics "
            f"({available_topics}) are fewer than required posts "
            f"({required_posts}). Using round-robin topic reuse with unique angles."
        )
    elif available_topics > required_posts:
        print(
            "Monthly recycler: available topics "
            f"({available_topics}) exceed required posts ({required_posts}). "
            "Using the first required topics for this cycle."
        )
    else:
        print(
            f"Monthly recycler: {available_topics} topics available for "
            f"{required_posts} required posts."
        )

    created = 0

    for index, day in enumerate(days):
        # Round-robin is intentional: it guarantees the month can be filled
        # even when the source library contains only one or a few topics.
        source = sources[index % available_topics]
        original_topic = source["الموضوع"].strip()
        angle = ANGLE_LIBRARY[index % len(ANGLE_LIBRARY)]
        recycled_topic = f"{original_topic} — زاوية جديدة: {angle}"

        row = {
            "ID": f"{current_key.replace('-', '')}-R{index + 1:02d}",
            "الموضوع": recycled_topic,
            "تاريخ النشر": (
                f"{current.year:04d}-{current.month:02d}-{day:02d}"
            ),
            "ساعة النشر": DEFAULT_POSTING_TIME,
            "نوع الجدولة": "DATE_TIME",
            "الحالة": "READY",
            "المصادر القانونية": source.get("المصادر القانونية", ""),
            "ملاحظات": (
                f"{RECYCLE_MARKER}:{current_key} | "
                f"الموضوع الأصلي: {original_topic} | "
                f"زاوية: {angle} | "
                "تم إنشاء النسخة الجديدة دون تعديل المصدر الأصلي | "
                f"ساعة النشر مثبتة تلقائيًا: {DEFAULT_POSTING_TIME}"
            ),
        }

        insert_row_at_top(
            service,
            spreadsheet_id,
            sheet_name,
            row,
        )
        created += 1

    print(
        f"Monthly recycler: created {created} rows for {current_key} "
        f"at {DEFAULT_POSTING_TIME} Cairo time."
    )
    return created
